language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson; fi

script: python setup.py test
